modLoader = "clojureloader"
loaderVersion = "[0.0.1,)"
issueTrackerURL = "https://github.com/lukebemish/pitchforks/issues"
license = "Insert License Here"

[[mods]]
modId = "pitchforks"
clojure = "com.github.lukebemish.pitchforks.common/init"
version = "${version}"
displayName = "Pitchforks"
authors = "Luke Bemish"
description = '''
Description here
'''
# logoFile = "icon.png"

[[dependencies.clojure_example_mod]]
modId = "forge"
mandatory = true
versionRange = "[38,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.clojure_example_mod]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.clojure_example_mod]]
modId = "clojurewrapper"
mandatory = true
versionRange = "[0.1.1,)"
ordering = "AFTER"
side = "BOTH"
